import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import LoginButton from "../components/auth/LoginButton";
import User from "../components/auth/User";
import { authOptions } from "./api/auth/[...nextauth]/route";
import "./globals.css";
import ErrorBoundary from "@/components/system/ErrorBoundary";
import { Providers } from "./providers";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getServerSession(authOptions);

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col bg-gray-900 text-white`}
			>
				<Providers session={session}>
					<ErrorBoundary>
						<header className="border-b border-gray-700 p-4">
							<div className="container mx-auto flex items-center justify-between">
								<Link href="/" className="text-xl font-bold">
									T3-NextChat
								</Link>
								<div className="flex items-center gap-4">
									<Link href="/settings" className="hover:underline">
										Settings
									</Link>
									<Link href="/kb" className="hover:underline">
										Knowledge Base
									</Link>
									{session?.user ? <User {...session.user} /> : <LoginButton />}
								</div>
							</div>
						</header>
						<main className="container mx-auto flex-grow p-4">{children}</main>
					</ErrorBoundary>
				</Providers>
			</body>
		</html>
	);
}
